no event manager applet ipsec-mpls-up authorization bypass
event manager applet ipsec-mpls-up authorization bypass
event syslog pattern "LINEPROTO-5-UPDOWN: Line protocol on Interface Tunnel100, changed state to up"
action 10 info type routername
action 20 syslog msg "Getting configuration url:http://10.112.83.119/$_info_routername-lan.cfg"
action 30 cli command "enable"
action 40 cli command "copy http://10.112.83.119:8080/$_info_routername-lan.cfg running-config" pattern "Destination filename"
action 50 cli command "running-config"
action 60 syslog msg "LAN configured by config-url"
